# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.fabric_api=0.134.1+1.21.9
build.fabric-permissions-api = 0.5.0

# Additional Dependencies Properties
# cloth-config, check https://modrinth.com/mod/cloth-config/versions?g=1.21.9&l=fabric
dep.cloth-config=qMxkrrmq
# flashback, check https://modrinth.com/mod/flashback/versions?g=1.21.9&l=fabric
dep.flashback=QpNVXwcn
# proxlib, check https://modrinth.com/mod/proxlib/versions?g=1.21.9&l=fabric
dep.proxlib=BAAQMXWP
# iris, check https://modrinth.com/mod/iris/versions?g=1.21.9&l=fabric
dep.iris=a98UkgML
# controlling, check https://modrinth.com/mod/controlling/versions?g=1.21.9&l=fabric
dep.controlling=gu0M6XOF
# searchables, check https://modrinth.com/mod/searchables/versions?g=1.21.9&l=fabric
dep.searchables=WkSxSOMO
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.9&l=fabric
dep.modmenu=pYbFlVtR
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.9&l=fabric
dep.yacl=3.8.0+1.21.9-fabric
# sodium, check https://modrinth.com/mod/sodium/versions?g=1.21.9&l=fabric
dep.sodium=sFfidWgd
# replaymod, check https://modrinth.com/mod/replaymod/versions?g=1.21.9&l=fabric
dep.replaymod=lwciuNZ7
# geckolib, check https://modrinth.com/mod/geckolib/versions?g=1.21.9&l=fabric
dep.geckolib=unknown
