# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.fabric_api=0.42.0+1.16
build.fabric-permissions-api = 0.3.1

# Additional Dependencies Properties
# cloth-config, check https://modrinth.com/mod/cloth-config/versions?g=1.16.5&l=fabric
dep.cloth-config=xMTUxQCV
# flashback, check https://modrinth.com/mod/flashback/versions?g=1.16.5&l=fabric
dep.flashback=unknown
# proxlib, check https://modrinth.com/mod/proxlib/versions?g=1.16.5&l=fabric
dep.proxlib=unknown
# iris, check https://modrinth.com/mod/iris/versions?g=1.16.5&l=fabric
dep.iris=1.4.5+1.16.5
# controlling, check https://modrinth.com/mod/controlling/versions?g=1.16.5&l=fabric
dep.controlling=Qt19ymXV
# searchables, check https://modrinth.com/mod/searchables/versions?g=1.16.5&l=fabric
dep.searchables=tRemkGX1
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.16.5&l=fabric
dep.modmenu=aShj7736
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.16.5&l=fabric
dep.yacl=unknown
# sodium, check https://modrinth.com/mod/sodium/versions?g=1.16.5&l=fabric
dep.sodium=mc1.16.5-0.2.0
# replaymod, check https://modrinth.com/mod/replaymod/versions?g=1.16.5&l=fabric
dep.replaymod=9iPcalHg
# geckolib, check https://modrinth.com/mod/geckolib/versions?g=1.16.5&l=fabric
dep.geckolib=UQGoJDhn
