import net.lopymine.utils.MossyUtils

plugins {
	id "net.lopymine.mossy-plugin-core" version "$mossy_plugin_version"
}

mossyDependencies {
	minecraft = stonecutter.current.project.substring(stonecutter.current.project.indexOf("-") + 1)
	lombok = prop("base.lombok_version")

	fabricApi = prop("build.fabric_api")
	fabricLoader = prop("build.fabric_loader")

	forge = prop("build.forge")

	neoForge = prop("build.neoforge")
	parchment = prop("build.parchment")

	additional {
		override("modCompileOnly", "flashback")
		override("modCompileOnly", "replaymod")
		//override("modCompileOnly", "iris")

		disable("fabric-permissions-api")
	}
}

loom.runConfigs.configureEach { config ->
	if (config.getEnvironment() == "client") {
		config.vmArg("-Dpatpat.debug=true")
	}
}

dependencies {
	def fpa = prop("build.fabric-permissions-api")
	if (stonecutter.current.parsed.matches(">=26.1") && fpa != "unknown") {
		include(implementation("me.lucko:fabric-permissions-api:${ fpa}")){
			exclude(group: "net.fabricmc.fabric-api")
		}
	} else if (fpa != "unknown") {
		include(modImplementation("me.lucko:fabric-permissions-api:${fpa}")){
			exclude(group: "net.fabricmc.fabric-api")
		}
	}

	testImplementation("net.fabricmc:fabric-loader-junit:${prop("build.fabric_loader")}")
}

stonecutter {
	replacements.string(current.parsed >= "26.1") {
		replace("net.minecraft.client.gui.GuiGraphics", "net.minecraft.client.gui.GuiGraphicsExtractor")
		replace("GuiGraphics", "GuiGraphicsExtractor")
		replace("import net.fabricmc.fabric.api.client.keybinding.v1.KeyBindingHelper;", "import net.fabricmc.fabric.api.client.keymapping.v1.KeyMappingHelper;")
		replace("KeyBindingHelper", "KeyMappingHelper")
		replace("KeyBindingHelper.registerKeyBinding", "KeyMappingHelper.registerKeyMapping")
		replace("import static net.fabricmc.fabric.api.client.command.v2.ClientCommandManager.argument;", "import static net.fabricmc.fabric.api.client.command.v2.ClientCommands.argument;")
		replace("import static net.fabricmc.fabric.api.client.command.v2.ClientCommandManager.literal;", "import static net.fabricmc.fabric.api.client.command.v2.ClientCommands.literal;")
		replace("END_WORLD_TICK", "END_LEVEL_TICK")
	}
}

// TODO: Добавить тесты на версию раньше, чем 1.18.2
if (stonecutter.compare(stonecutter.current.version.toString(), "1.18.2") >= 0) {
	test {
		useJUnitPlatform()
	}
}

test {
	failOnNoDiscoveredTests = false
}

fabricApi {
	configureTests {
		createSourceSet = true
		modId = "patpat-mod-test-${project.name}"
		enableGameTests = true // Default is true
		enableClientGameTests = true // Default is true
		eula = true // By setting this to true, you agree to the Minecraft EULA.
	}
}

tasks.named("runClientGameTest", JavaExec) {
	jvmArgs "-ea"
}

configurations.configureEach {
	resolutionStrategy {
		force("net.fabricmc:fabric-loader:${prop("build.fabric_loader")}")
	}
}

stonecutter {
	var buildTime = (int) (System.currentTimeMillis() / 10000) - 174611089
	var buildCodeTime = String.format("%07x", buildTime & 0xFFFFFFF)
	swaps["build_code_time"] = "\"${buildCodeTime}\";".toString()
	dependencies["yacl"] = MossyUtils.substringBefore(prop("dep.yacl"), "+")

//	replacements.regex(current.parsed.matches(">=1.21.11")) {
//		replace(
//				"(^|[^A-Za-z0-9_])ResourceLocation([^A-Za-z0-9_]|\$)", "\$1Identifier\$2",
//				"(^|[^A-Za-z0-9_])Identifier([^A-Za-z0-9_]|\$)", "\$1ResourceLocation\$2"
//		)
//	}

	replacements.string(current.parsed < "1.17") {
		replace("ControllingOptionsScreenMixin", "ControllingOptionsScreenMixin")
		replace("ControllingOptionsScreen", "ControlsSettingsGuiNew")
	}

	replacements.string(current.parsed >= "1.18") {
		replace("KeyBindsScreenAccessor", "KeyBindsScreenAccessor")
		replace("KeyBindsScreenMixin", "KeyBindsScreenMixin")
		replace("NewKeyBindsScreen", "NewKeyBindsScreen")
		replace("ControlsScreen", "KeyBindsScreen")
	}

	replacements.string(current.parsed >= "1.21") {
		replace("import net.minecraft.client.gui.screens.controls.*;", "import net.minecraft.client.gui.screens.options.controls.*;")
	}

	replacements.string(current.parsed >= "1.21.9") {
		replace("int keyCode, int scanCode, int modifiers", "net.minecraft.client.input.KeyEvent event")
		replace("double mouseX, double mouseY, int button", "net.minecraft.client.input.MouseButtonEvent event, boolean bl")
	}

	replacements.string(current.parsed >= "1.21.11") {
		replace("ProxPacketIdentifier", "ProxPacketIdentifier")
		replace("ResourceLocation", "Identifier")
		replace(".location()", ".identifier()")
		replace("RenderType", "RenderTypes")
	}

}

stonecutter.filters.exclude("**/*.accesswidener")
stonecutter.filters.exclude("**/*.classTweaker")

jar {
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

processResources {
	from("../../patpat-languages-files/lang") {
		into "assets/${prop("data.mod_id")}/lang/"
		eachFile { file ->
			if (!file.isDirectory()) {
				// Client requires lang files in lower case
				file.name = file.name.toLowerCase()
			}
		}
	}
}

String prop(String key) {
	return findProperty(key).toString()
}
