import net.lopymine.utils.MossyUtils

plugins {
	id "net.lopymine.mossy-plugin-core" version "$mossy_plugin_version"
}

mossyDependencies {
	minecraft = stonecutter.current.project.substring(stonecutter.current.project.indexOf("-") + 1)
	lombok = prop("base.lombok_version")

	fabricApi = prop("build.fabric_api")
	fabricLoader = prop("build.fabric_loader")

	forge = prop("build.forge")

	neoForge = prop("build.neoforge")
	parchment = prop("build.parchment")

	if (sc.current.project.startsWith("forge-") && sc.current.version.toString() == "1.20.1") {
		disableMixinAp = "true"
	}

	additional {
		override("mossyCompileOnly", "flashback")
		override("mossyCompileOnly", "replaymod")

		disable("fabric-permissions-api")
	}
}

def fabric = sc.current.project.contains("fabric")
def forge = sc.current.project.startsWith("forge-")

repositories {
	maven {
		name = "Sinytra"
		url = "https://maven.su5ed.dev/releases"
	}
}

dependencies {
	if (fabric) {
		def fpa = prop("build.fabric-permissions-api")
		if (fpa != "unknown") {
			include(mossyImplementation("me.lucko:fabric-permissions-api:${fpa}")){
				exclude(group: "net.fabricmc.fabric-api")
			}
		}

		testImplementation("net.fabricmc:fabric-loader-junit:${prop("build.fabric_loader")}")
	}

	if (forge) {
		annotationProcessor("net.fabricmc:sponge-mixin:0.16.5+mixin.0.8.7")
		modImplementation("maven.modrinth:mixinbooster:0.1.2+1.20.1")
	}
}

test {
	failOnNoDiscoveredTests = false
}

if (fabric) {
	if (stonecutter.compare(stonecutter.current.version.toString(), "1.18.2") >= 0 && stonecutter.compare(stonecutter.current.version.toString(), "1.21.11") < 0) {
		test {
			useJUnitPlatform()
		}
	}

	loom.runConfigs.configureEach { config ->
		if (config.getEnvironment() == "client") {
			config.vmArg("-Dpatpat.debug=true")
		}
	}

	fabricApi {
		configureTests {
			createSourceSet = true
			modId = "patpat-mod-test-${project.name}"
			enableGameTests = true // Default is true
			enableClientGameTests = true // Default is true
			eula = true // By setting this to true, you agree to the Minecraft EULA.
		}
	}

	tasks.named("runClientGameTest", JavaExec) {
		jvmArgs "-ea"
	}

	configurations.configureEach {
		resolutionStrategy {
			force("net.fabricmc:fabric-loader:${prop("build.fabric_loader")}")
		}
	}
}

stonecutter {
	var buildTime = (int) (System.currentTimeMillis() / 10000) - 174611089
	var buildCodeTime = String.format("%07x", buildTime & 0xFFFFFFF)

	swaps["build_code_time"] = "\"${buildCodeTime}\";".toString()
	dependencies["yacl"] = MossyUtils.substringBefore(prop("dep.yacl"), "+")

	replacements.string(current.parsed < "1.17") {
		replace("ControllingOptionsScreenMixin", "ControllingOptionsScreenMixin")
		replace("ControllingOptionsScreen", "ControlsSettingsGuiNew")
	}

	replacements.string(current.parsed >= "1.18") {
		replace("KeyBindsScreenAccessor", "KeyBindsScreenAccessor")
		replace("KeyBindsScreenMixin", "KeyBindsScreenMixin")
		replace("NewKeyBindsScreen", "NewKeyBindsScreen")
		replace("ControlsScreen", "KeyBindsScreen")
	}

	replacements.string(current.parsed >= "1.21") {
		replace("import net.minecraft.client.gui.screens.controls.*;", "import net.minecraft.client.gui.screens.options.controls.*;")
	}

	replacements.string(current.parsed >= "1.21.9") {
		replace("int keyCode, int scanCode, int modifiers", "net.minecraft.client.input.KeyEvent event")
		replace("double mouseX, double mouseY, int button", "net.minecraft.client.input.MouseButtonEvent event, boolean bl")
	}

	replacements.string(current.parsed >= "1.21.11") {
		replace("ProxPacketIdentifier", "ProxPacketIdentifier")
		replace("ResourceLocation", "Identifier")
		replace(".location()", ".identifier()")
		replace("RenderType", "RenderTypes")
	}

	constants["debug_mode"] = false
}

stonecutter.filters.exclude("**/*.accesswidener")
stonecutter.filters.exclude("**/*.cfg")
stonecutter.filters.exclude("**/*.classTweaker")

jar {
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

processResources {
	from("../../patpat-languages-files/lang") {
		into "assets/${prop("data.mod_id")}/lang/"
		eachFile { file ->
			if (!file.isDirectory()) {
				// Client requires lang files in lower case
				file.name = file.name.toLowerCase()
			}
		}
	}
}

String prop(String key) {
	return findProperty(key).toString()
}