# # # # # # # # # # # # # #
#    Gradle Properties    #
# # # # # # # # # # # # # #

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx12G
org.gradle.parallel=true

# Mossy Plugin
mossy_plugin_version = 3.2.0

# Stonecutter
dev.kikugie.stonecutter.hard_mode=true

# Mod Properties
data.mod_id = patpat
data.mod_name = PatPat
data.mod_version = 1.2.5
data.mod_group = net.lopymine.patpat
data.mod_maven_group = net.lopymine
data.mixin_configs = controlling geckolib
data.sides = client

data.mod_description = Simple Client and (Optional) Server side Fabric mod for patting any (living) mobs!
data.mod_authors = LopyMine, nikita51
data.github_mod_author = LopyMine
data.mod_license = LGPL-3.0-only
data.server_config_version = 1.0.0
data.client_config_version = 1.0.1

# Main Dependencies
base.lombok_version = 1.18.42
base.mixinextras_version = 0.4.1
base.mixin_version = 0.8.5

# Multi-Versions Properties
fabric.multi_versions = 26.1-pre-2

# Mod Loaders
mod_loaders = fabric

# Mod Loader Dependencies Dependencies
build.fabric_loader = 0.18.4
build.fabric_api = [VERSIONED]
build.neoforge = [VERSIONED]
build.parchment = [VERSIONED]
build.forge = [VERSIONED]

# Additional Dependencies, "dep." is important
dep.yacl = [VERSIONED]
dep.modmenu = [VERSIONED]
dep.cloth-config = [VERSIONED]
dep.replaymod = [VERSIONED]
dep.geckolib = [VERSIONED]
dep.flashback = [VERSIONED]
dep.proxlib = [VERSIONED]
dep.controlling = [VERSIONED]
dep.searchables = [VERSIONED]

# # # # # # # # # # # # # #
#  Publication Properties #
# # # # # # # # # # # # # #

# Versions Specifications
fabric.versions_specifications = 1.21.10
#neoforge.versions_specifications = 1.21.10
#forge.versions_specifications = 1.21.10

# Version Type [RELEASE, BETA, ALPHA]
version_type = RELEASE

# Imitation of Publishing. Set to "true" for testing
test_publish = false

# Project IDs
modrinth_id = dw7LChq9
curseforge_id = 1105962

# CurseForge Settings
is_for_client = true
is_for_server = true
max_java_version = 21

# Fabric Mod Depends
fabric.depends_requires = fabric-api
fabric.depends_optional = modmenu yacl cloth-config proxlib
fabric.depends_incompatible = none
fabric.depends_embeds  = none
#
## NeoForge Mod Depends
#neoforge.depends_requires = none
#neoforge.depends_optional = yacl
#neoforge.depends_incompatible = none
#neoforge.depends_embeds  = none
#
## Forge Mod Depends
#forge.depends_requires = none
#forge.depends_optional = yacl
#forge.depends_incompatible = none
#forge.depends_embeds  = none
