# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# NeoForge Properties, check https://neoforged.net/
build.neoforge=21.9.16-beta
build.parchment=2025.10.05

# Additional Dependencies Properties
# cloth-config, check https://modrinth.com/mod/cloth-config/versions?g=1.21.9&l=neoforge
dep.cloth-config=AzRGxC9j
# flashback, check https://modrinth.com/mod/flashback/versions?g=1.21.9&l=neoforge
dep.flashback=unknown
# proxlib, check https://modrinth.com/mod/proxlib/versions?g=1.21.9&l=neoforge
dep.proxlib=unknown
# iris, check https://modrinth.com/mod/iris/versions?g=1.21.9&l=neoforge
dep.iris=unknown
# controlling, check https://modrinth.com/mod/controlling/versions?g=1.21.9&l=neoforge
dep.controlling=y0iRFmNm
# searchables, check https://modrinth.com/mod/searchables/versions?g=1.21.9&l=neoforge
dep.searchables=Pr3PYkuE
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.9&l=neoforge
dep.modmenu=unknown
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.9&l=neoforge
dep.yacl=3.8.0+1.21.9-neoforge
# sodium, check https://modrinth.com/mod/sodium/versions?g=1.21.9&l=neoforge
dep.sodium=unknown
# replaymod, check https://modrinth.com/mod/replaymod/versions?g=1.21.9&l=neoforge
dep.replaymod=unknown
# geckolib, check https://modrinth.com/mod/geckolib/versions?g=1.21.9&l=neoforge
dep.geckolib=unknown
