# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# NeoForge Properties, check https://neoforged.net/
build.neoforge=21.1.217
build.parchment=2024.11.17

# Additional Dependencies Properties
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.1&l=neoforge
dep.modmenu=unknown
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.1&l=neoforge
dep.yacl=3.8.1+1.21.1-neoforge
# cloth-config, check https://modrinth.com/mod/cloth-config/versions?g=1.21.1&l=neoforge
dep.cloth-config=izKINKFg
# flashback, check https://modrinth.com/mod/flashback/versions?g=1.21.1&l=neoforge
dep.flashback=unknown
# proxlib, check https://modrinth.com/mod/proxlib/versions?g=1.21.1&l=neoforge
dep.proxlib=unknown
# controlling, check https://modrinth.com/mod/controlling/versions?g=1.21.1&l=neoforge
dep.controlling=FaNppCJJ
# searchables, check https://modrinth.com/mod/searchables/versions?g=1.21.1&l=neoforge
dep.searchables=iEE85X0w
# replaymod, check https://modrinth.com/mod/replaymod/versions?g=1.21.1&l=neoforge
dep.replaymod=unknown
# geckolib, check https://modrinth.com/mod/geckolib/versions?g=1.21.1&l=neoforge
dep.geckolib=4.8.2
