# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# NeoForge Properties, check https://neoforged.net/
build.neoforge=20.2.93
build.parchment=2023.12.10

# Additional Dependencies Properties
# cloth-config, check https://modrinth.com/mod/cloth-config/versions?g=1.20.2&l=neoforge
dep.cloth-config=mAH9Nl59
# flashback, check https://modrinth.com/mod/flashback/versions?g=1.20.2&l=neoforge
dep.flashback=unknown
# proxlib, check https://modrinth.com/mod/proxlib/versions?g=1.20.2&l=neoforge
dep.proxlib=unknown
# iris, check https://modrinth.com/mod/iris/versions?g=1.20.2&l=neoforge
dep.iris=unknown
# controlling, check https://modrinth.com/mod/controlling/versions?g=1.20.2&l=neoforge
dep.controlling=coj1ynEJ
# searchables, check https://modrinth.com/mod/searchables/versions?g=1.20.2&l=neoforge
dep.searchables=IrC7uNUe
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.20.2&l=neoforge
dep.modmenu=unknown
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.20.2&l=neoforge
dep.yacl=3.3.0+1.20.4
# sodium, check https://modrinth.com/mod/sodium/versions?g=1.20.2&l=neoforge
dep.sodium=unknown
# replaymod, check https://modrinth.com/mod/replaymod/versions?g=1.20.2&l=neoforge
dep.replaymod=unknown
# geckolib, check https://modrinth.com/mod/geckolib/versions?g=1.20.2&l=neoforge
dep.geckolib=t7b6BuZg
