# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# NeoForge Properties, check https://neoforged.net/
build.neoforge=21.11.40-beta
build.parchment=2025.12.20

# Additional Dependencies Properties
# cloth-config, check https://modrinth.com/mod/cloth-config/versions?g=1.21.11&l=neoforge
dep.cloth-config=Wsus0EWg
# flashback, check https://modrinth.com/mod/flashback/versions?g=1.21.11&l=neoforge
dep.flashback=unknown
# proxlib, check https://modrinth.com/mod/proxlib/versions?g=1.21.11&l=neoforge
dep.proxlib=unknown
# controlling, check https://modrinth.com/mod/controlling/versions?g=1.21.11&l=neoforge
dep.controlling=hdMpvWkx
# searchables, check https://modrinth.com/mod/searchables/versions?g=1.21.11&l=neoforge
dep.searchables=Q0OwTB2u
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.11&l=neoforge
dep.modmenu=unknown
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.11&l=neoforge
dep.yacl=3.8.2+1.21.11-neoforge
# replaymod, check https://modrinth.com/mod/replaymod/versions?g=1.21.11&l=neoforge
dep.replaymod=unknown
# geckolib, check https://modrinth.com/mod/geckolib/versions?g=1.21.11&l=neoforge
dep.geckolib=FpONDAt3
