# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.fabric_api=0.46.1+1.17
build.fabric-permissions-api = 0.3.1

# Additional Dependencies Properties
# cloth-config, check https://modrinth.com/mod/cloth-config/versions?g=1.17.1&l=fabric
dep.cloth-config=gb0cZ2Qp
# flashback, check https://modrinth.com/mod/flashback/versions?g=1.17.1&l=fabric
dep.flashback=unknown
# proxlib, check https://modrinth.com/mod/proxlib/versions?g=1.17.1&l=fabric
dep.proxlib=unknown
# iris, check https://modrinth.com/mod/iris/versions?g=1.17.1&l=fabric
dep.iris=pkGrlTNQ
# controlling, check https://modrinth.com/mod/controlling/versions?g=1.17.1&l=fabric
dep.controlling=yhUO28QC
# searchables, check https://modrinth.com/mod/searchables/versions?g=1.17.1&l=fabric
dep.searchables=YrZSPg5T
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.17.1&l=fabric
dep.modmenu=7kh2ofyR
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.17.1&l=fabric
dep.yacl=unknown
# sodium, check https://modrinth.com/mod/sodium/versions?g=1.17.1&l=fabric
dep.sodium=mc1.17.1-0.3.4
# replaymod, check https://modrinth.com/mod/replaymod/versions?g=1.17.1&l=fabric
dep.replaymod=1.17.1-2.6.20
# geckolib, check https://modrinth.com/mod/geckolib/versions?g=1.17.1&l=fabric
dep.geckolib=qL484XIi
