# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Forge Properties, check https://files.minecraftforge.net/net/minecraftforge/forge/index_1.17.1.html
build.forge=1.17.1-37.1.1
build.parchment=2021.12.12

# Additional Dependencies Properties
# cloth-config, check https://modrinth.com/mod/cloth-config/versions?g=1.17.1&l=forge
dep.cloth-config=GH6kNTCk
# flashback, check https://modrinth.com/mod/flashback/versions?g=1.17.1&l=forge
dep.flashback=unknown
# proxlib, check https://modrinth.com/mod/proxlib/versions?g=1.17.1&l=forge
dep.proxlib=unknown
# iris, check https://modrinth.com/mod/iris/versions?g=1.17.1&l=forge
dep.iris=unknown
# controlling, check https://modrinth.com/mod/controlling/versions?g=1.17.1&l=forge
dep.controlling=l9JZQS1e
# searchables, check https://modrinth.com/mod/searchables/versions?g=1.17.1&l=forge
dep.searchables=xOO5vAnB
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.17.1&l=forge
dep.modmenu=unknown
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.17.1&l=forge
dep.yacl=unknown
# sodium, check https://modrinth.com/mod/sodium/versions?g=1.17.1&l=forge
dep.sodium=unknown
# replaymod, check https://modrinth.com/mod/replaymod/versions?g=1.17.1&l=forge
dep.replaymod=unknown
# geckolib, check https://modrinth.com/mod/geckolib/versions?g=1.17.1&l=forge
dep.geckolib=qL484XIi
