# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.fabric_api=0.128.2+1.21.6
build.fabric-permissions-api = 0.4.0

# Additional Dependencies Properties
# cloth-config, check https://modrinth.com/mod/cloth-config/versions?g=1.21.6&l=fabric
dep.cloth-config=cz0b1j8R
# flashback, check https://modrinth.com/mod/flashback/versions?g=1.21.6&l=fabric
dep.flashback=X3J8u7wy
# proxlib, check https://modrinth.com/mod/proxlib/versions?g=1.21.6&l=fabric
dep.proxlib=BAAQMXWP
# iris, check https://modrinth.com/mod/iris/versions?g=1.21.6&l=fabric
dep.iris=Rhzf61g1
# controlling, check https://modrinth.com/mod/controlling/versions?g=1.21.6&l=fabric
dep.controlling=IzCLUaM4
# searchables, check https://modrinth.com/mod/searchables/versions?g=1.21.6&l=fabric
dep.searchables=shmjV0gp
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.6&l=fabric
dep.modmenu=ku5NivOP
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.6&l=fabric
dep.yacl=3.8.2+1.21.6-fabric
# sodium, check https://modrinth.com/mod/sodium/versions?g=1.21.6&l=fabric
dep.sodium=7pwil2dy
# replaymod, check https://modrinth.com/mod/replaymod/versions?g=1.21.6&l=fabric
dep.replaymod=TUHG3lET
# geckolib, check https://modrinth.com/mod/geckolib/versions?g=1.21.6&l=fabric
dep.geckolib=cMt8HLkd
