# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.fabric_api=0.128.2+1.21.5
build.fabric-permissions-api = 0.3.3

# Additional Dependencies Properties
# cloth-config, check https://modrinth.com/mod/cloth-config/versions?g=1.21.5&l=fabric
dep.cloth-config=qA00xo1O
# flashback, check https://modrinth.com/mod/flashback/versions?g=1.21.5&l=fabric
dep.flashback=JUF5ddLV
# proxlib, check https://modrinth.com/mod/proxlib/versions?g=1.21.5&l=fabric
dep.proxlib=BAAQMXWP
# iris, check https://modrinth.com/mod/iris/versions?g=1.21.5&l=fabric
dep.iris=1.8.11+1.21.5-fabric
# controlling, check https://modrinth.com/mod/controlling/versions?g=1.21.5&l=fabric
dep.controlling=3qTTC7U1
# searchables, check https://modrinth.com/mod/searchables/versions?g=1.21.5&l=fabric
dep.searchables=Z4JnRLbU
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.5&l=fabric
dep.modmenu=2ZvBR7XI
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.5&l=fabric
dep.yacl=3.8.2+1.21.5-fabric
# sodium, check https://modrinth.com/mod/sodium/versions?g=1.21.5&l=fabric
dep.sodium=mc1.21.5-0.6.13-fabric
# replaymod, check https://modrinth.com/mod/replaymod/versions?g=1.21.5&l=fabric
dep.replaymod=1.21.5-2.6.23
# geckolib, check https://modrinth.com/mod/geckolib/versions?g=1.21.5&l=fabric
dep.geckolib=AyXpbm2h
