# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Forge Properties, check https://files.minecraftforge.net/net/minecraftforge/forge/index_1.19.4.html
build.forge=1.19.4-45.4.3
build.parchment=2023.06.26

# Additional Dependencies Properties
# cloth-config, check https://modrinth.com/mod/cloth-config/versions?g=1.19.4&l=forge
dep.cloth-config=mwddirHR
# flashback, check https://modrinth.com/mod/flashback/versions?g=1.19.4&l=forge
dep.flashback=unknown
# proxlib, check https://modrinth.com/mod/proxlib/versions?g=1.19.4&l=forge
dep.proxlib=unknown
# iris, check https://modrinth.com/mod/iris/versions?g=1.19.4&l=forge
dep.iris=unknown
# controlling, check https://modrinth.com/mod/controlling/versions?g=1.19.4&l=forge
dep.controlling=V5rSFq4V
# searchables, check https://modrinth.com/mod/searchables/versions?g=1.19.4&l=forge
dep.searchables=erSt9y38
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.19.4&l=forge
dep.modmenu=unknown
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.19.4&l=forge
dep.yacl=3.1.1+1.19.4-forge
# sodium, check https://modrinth.com/mod/sodium/versions?g=1.19.4&l=forge
dep.sodium=unknown
# replaymod, check https://modrinth.com/mod/replaymod/versions?g=1.19.4&l=forge
dep.replaymod=unknown
# geckolib, check https://modrinth.com/mod/geckolib/versions?g=1.19.4&l=forge
dep.geckolib=ApKEGN4z
