# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.fabric_api=0.153.0+26.2
build.fabric-permissions-api = 0.7.0

# Additional Dependencies Properties
# cloth-config, check https://modrinth.com/mod/cloth-config/versions?g=26.2&l=fabric
dep.cloth-config=26.2.155+fabric
# flashback, check https://modrinth.com/mod/flashback/versions?g=26.2&l=fabric
dep.flashback=cGezdWTX
# proxlib, check https://modrinth.com/mod/proxlib/versions?g=26.2&l=fabric
dep.proxlib=unknown
# iris, check https://modrinth.com/mod/iris/versions?g=26.2&l=fabric
dep.iris=1.11.1+26.2-fabric
# controlling, check https://modrinth.com/mod/controlling/versions?g=26.2&l=fabric
dep.controlling=rAp2jljs
# searchables, check https://modrinth.com/mod/searchables/versions?g=26.2&l=fabric
dep.searchables=bvFby61J
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=26.2&l=fabric
dep.modmenu=20.0.0-beta.4
# yacl, check https://modrinth.com/mod/yacl/versions?g=26.2&l=fabric
dep.yacl=3.9.4+26.2-fabric
# sodium, check https://modrinth.com/mod/sodium/versions?g=26.2&l=fabric
dep.sodium=mc26.2-0.9.0-fabric
# replaymod, check https://modrinth.com/mod/replaymod/versions?g=26.2&l=fabric
dep.replaymod=unknown
# geckolib, check https://modrinth.com/mod/geckolib/versions?g=26.2&l=fabric
dep.geckolib=GdrAq4td
