# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Forge Properties, check https://files.minecraftforge.net/net/minecraftforge/forge/index_1.20.1.html
build.forge=1.20.1-47.4.18
build.parchment=2023.09.03

# Additional Dependencies Properties
# cloth-config, check https://modrinth.com/mod/cloth-config/versions?g=1.20.1&l=forge
dep.cloth-config=t8TXrZvZ
# flashback, check https://modrinth.com/mod/flashback/versions?g=1.20.1&l=forge
dep.flashback=unknown
# proxlib, check https://modrinth.com/mod/proxlib/versions?g=1.20.1&l=forge
dep.proxlib=unknown
# controlling, check https://modrinth.com/mod/controlling/versions?g=1.20.1&l=forge
dep.controlling=LH6Bi6Am
# searchables, check https://modrinth.com/mod/searchables/versions?g=1.20.1&l=forge
dep.searchables=PM9yAW1G
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.20.1&l=forge
dep.modmenu=unknown
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.20.1&l=forge
dep.yacl=3.6.6+1.20.1-forge
# replaymod, check https://modrinth.com/mod/replaymod/versions?g=1.20.1&l=forge
dep.replaymod=unknown
# geckolib, check https://modrinth.com/mod/geckolib/versions?g=1.20.1&l=forge
dep.geckolib=HVdLnQMI
