# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.fabric_api=0.155.2+26.1.2
build.fabric-permissions-api = 0.7.0

# Additional Dependencies Properties
# cloth-config, check https://modrinth.com/mod/cloth-config/versions?g=26.1&l=fabric
dep.cloth-config=unknown
# flashback, check https://modrinth.com/mod/flashback/versions?g=26.1&l=fabric
dep.flashback=unknown
# proxlib, check https://modrinth.com/mod/proxlib/versions?g=26.1&l=fabric
dep.proxlib=unknown
# controlling, check https://modrinth.com/mod/controlling/versions?g=26.1&l=fabric
dep.controlling=26.1.0.1
# searchables, check https://modrinth.com/mod/searchables/versions?g=26.1&l=fabric
dep.searchables=jayVAixj
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=26.1&l=fabric
dep.modmenu=lWZE38V3
# yacl, check https://modrinth.com/mod/yacl/versions?g=26.1&l=fabric
dep.yacl=3.9.0+26.1-fabric
# replaymod, check https://modrinth.com/mod/replaymod/versions?g=26.1&l=fabric
dep.replaymod=unknown
# geckolib, check https://modrinth.com/mod/geckolib/versions?g=26.1&l=fabric
dep.geckolib=yUpAp23B
# iris, check https://modrinth.com/mod/iris/versions?g=26.1&l=fabric
dep.iris=1.10.7+26.1-fabric
# sodium, check https://modrinth.com/mod/sodium/versions?g=26.1&l=fabric
dep.sodium=mc26.1-0.8.7-fabric
