# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.fabric_api=0.160.7+26.3
build.fabric-permissions-api = 0.7.0

# Additional Dependencies Properties
# cloth-config, check https://modrinth.com/mod/cloth-config/versions?g=26.3&l=fabric
dep.cloth-config=26.3.158+fabric
# flashback, check https://modrinth.com/mod/flashback/versions?g=26.3&l=fabric
dep.flashback=cGezdWTX
# proxlib, check https://modrinth.com/mod/proxlib/versions?g=26.3&l=fabric
dep.proxlib=0.2.4+26.1
# iris, check https://modrinth.com/mod/iris/versions?g=26.3&l=fabric
dep.iris=1.11.6+26.3-fabric
# controlling, check https://modrinth.com/mod/controlling/versions?g=26.3&l=fabric
dep.controlling=26.3.1
# searchables, check https://modrinth.com/mod/searchables/versions?g=26.3&l=fabric
dep.searchables=RlPMfNdS
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=26.3&l=fabric
dep.modmenu=21.0.0-beta.1
# yacl, check https://modrinth.com/mod/yacl/versions?g=26.3&l=fabric
dep.yacl=3.9.6+26.3-fabric
# sodium, check https://modrinth.com/mod/sodium/versions?g=26.3&l=fabric
dep.sodium=mc26.3-0.9.2-fabric
# replaymod, check https://modrinth.com/mod/replaymod/versions?g=26.3&l=fabric
dep.replaymod=26.2-2.6.27
# geckolib, check https://modrinth.com/mod/geckolib/versions?g=26.3&l=fabric
dep.geckolib=1VWnZPbQ
